name: Publish Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Publish to registry
      uses: elgohr/Publish-Docker-Github-Action@main
      with:
        registry: docker.pkg.github.com
        name: docker.pkg.github.com/firaliexpress/top-api/top-api
        username: ${{ github.actor }}
        password: ${{ secrets.GIT_AUTH_TOKEN }}
        tags: "develop"
        